# YAML/Docker - Medium

version: '3'

services:
  # Define your services here
  service1:
    image: your-image-1
    ports:
      - "8080:80"
    networks:
      - mynetwork

  service2:
    image: your-image-2
    ports:
      - "8081:80"
    networks:
      - mynetwork

networks:
  # Define your networks here
  mynetwork:
    driver: bridge
